/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignUpIndexRouteImport } from './routes/sign-up/index'
import { Route as SignInIndexRouteImport } from './routes/sign-in/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as OrganizationsIndexRouteImport } from './routes/organizations/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as OrganizationsNewIndexRouteImport } from './routes/organizations/new/index'
import { Route as OrganizationsInvitationsIndexRouteImport } from './routes/organizations/invitations/index'
import { Route as DashboardSettingsIndexRouteImport } from './routes/dashboard/settings/index'
import { Route as DashboardRolesIndexRouteImport } from './routes/dashboard/roles/index'
import { Route as DashboardMembersIndexRouteImport } from './routes/dashboard/members/index'
import { Route as DashboardInvitationsIndexRouteImport } from './routes/dashboard/invitations/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as DashboardRolesNewIndexRouteImport } from './routes/dashboard/roles/new/index'
import { Route as DashboardMembersInviteIndexRouteImport } from './routes/dashboard/members/invite/index'
import { Route as DashboardMembersMemberIdEditIndexRouteImport } from './routes/dashboard/members/$memberId/edit/index'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpIndexRoute = SignUpIndexRouteImport.update({
  id: '/sign-up/',
  path: '/sign-up/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInIndexRoute = SignInIndexRouteImport.update({
  id: '/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsIndexRoute = OrganizationsIndexRouteImport.update({
  id: '/organizations/',
  path: '/organizations/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const OrganizationsNewIndexRoute = OrganizationsNewIndexRouteImport.update({
  id: '/organizations/new/',
  path: '/organizations/new/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsInvitationsIndexRoute =
  OrganizationsInvitationsIndexRouteImport.update({
    id: '/organizations/invitations/',
    path: '/organizations/invitations/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardSettingsIndexRoute = DashboardSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardRolesIndexRoute = DashboardRolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardMembersIndexRoute = DashboardMembersIndexRouteImport.update({
  id: '/members/',
  path: '/members/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardInvitationsIndexRoute =
  DashboardInvitationsIndexRouteImport.update({
    id: '/invitations/',
    path: '/invitations/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRolesNewIndexRoute = DashboardRolesNewIndexRouteImport.update({
  id: '/roles/new/',
  path: '/roles/new/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardMembersInviteIndexRoute =
  DashboardMembersInviteIndexRouteImport.update({
    id: '/members/invite/',
    path: '/members/invite/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardMembersMemberIdEditIndexRoute =
  DashboardMembersMemberIdEditIndexRouteImport.update({
    id: '/members/$memberId/edit/',
    path: '/members/$memberId/edit/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/organizations/': typeof OrganizationsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/sign-in/': typeof SignInIndexRoute
  '/sign-up/': typeof SignUpIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/invitations/': typeof DashboardInvitationsIndexRoute
  '/dashboard/members/': typeof DashboardMembersIndexRoute
  '/dashboard/roles/': typeof DashboardRolesIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/organizations/invitations/': typeof OrganizationsInvitationsIndexRoute
  '/organizations/new/': typeof OrganizationsNewIndexRoute
  '/dashboard/members/invite/': typeof DashboardMembersInviteIndexRoute
  '/dashboard/roles/new/': typeof DashboardRolesNewIndexRoute
  '/dashboard/members/$memberId/edit/': typeof DashboardMembersMemberIdEditIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/organizations': typeof OrganizationsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/sign-in': typeof SignInIndexRoute
  '/sign-up': typeof SignUpIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/invitations': typeof DashboardInvitationsIndexRoute
  '/dashboard/members': typeof DashboardMembersIndexRoute
  '/dashboard/roles': typeof DashboardRolesIndexRoute
  '/dashboard/settings': typeof DashboardSettingsIndexRoute
  '/organizations/invitations': typeof OrganizationsInvitationsIndexRoute
  '/organizations/new': typeof OrganizationsNewIndexRoute
  '/dashboard/members/invite': typeof DashboardMembersInviteIndexRoute
  '/dashboard/roles/new': typeof DashboardRolesNewIndexRoute
  '/dashboard/members/$memberId/edit': typeof DashboardMembersMemberIdEditIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/organizations/': typeof OrganizationsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/sign-in/': typeof SignInIndexRoute
  '/sign-up/': typeof SignUpIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/invitations/': typeof DashboardInvitationsIndexRoute
  '/dashboard/members/': typeof DashboardMembersIndexRoute
  '/dashboard/roles/': typeof DashboardRolesIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/organizations/invitations/': typeof OrganizationsInvitationsIndexRoute
  '/organizations/new/': typeof OrganizationsNewIndexRoute
  '/dashboard/members/invite/': typeof DashboardMembersInviteIndexRoute
  '/dashboard/roles/new/': typeof DashboardRolesNewIndexRoute
  '/dashboard/members/$memberId/edit/': typeof DashboardMembersMemberIdEditIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/'
    | '/organizations/'
    | '/settings/'
    | '/sign-in/'
    | '/sign-up/'
    | '/api/auth/$'
    | '/dashboard/invitations/'
    | '/dashboard/members/'
    | '/dashboard/roles/'
    | '/dashboard/settings/'
    | '/organizations/invitations/'
    | '/organizations/new/'
    | '/dashboard/members/invite/'
    | '/dashboard/roles/new/'
    | '/dashboard/members/$memberId/edit/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/organizations'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/api/auth/$'
    | '/dashboard/invitations'
    | '/dashboard/members'
    | '/dashboard/roles'
    | '/dashboard/settings'
    | '/organizations/invitations'
    | '/organizations/new'
    | '/dashboard/members/invite'
    | '/dashboard/roles/new'
    | '/dashboard/members/$memberId/edit'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/'
    | '/organizations/'
    | '/settings/'
    | '/sign-in/'
    | '/sign-up/'
    | '/api/auth/$'
    | '/dashboard/invitations/'
    | '/dashboard/members/'
    | '/dashboard/roles/'
    | '/dashboard/settings/'
    | '/organizations/invitations/'
    | '/organizations/new/'
    | '/dashboard/members/invite/'
    | '/dashboard/roles/new/'
    | '/dashboard/members/$memberId/edit/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  OrganizationsIndexRoute: typeof OrganizationsIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  SignInIndexRoute: typeof SignInIndexRoute
  SignUpIndexRoute: typeof SignUpIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  OrganizationsInvitationsIndexRoute: typeof OrganizationsInvitationsIndexRoute
  OrganizationsNewIndexRoute: typeof OrganizationsNewIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up/': {
      id: '/sign-up/'
      path: '/sign-up'
      fullPath: '/sign-up/'
      preLoaderRoute: typeof SignUpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/': {
      id: '/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in/'
      preLoaderRoute: typeof SignInIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/': {
      id: '/organizations/'
      path: '/organizations'
      fullPath: '/organizations/'
      preLoaderRoute: typeof OrganizationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/organizations/new/': {
      id: '/organizations/new/'
      path: '/organizations/new'
      fullPath: '/organizations/new/'
      preLoaderRoute: typeof OrganizationsNewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/invitations/': {
      id: '/organizations/invitations/'
      path: '/organizations/invitations'
      fullPath: '/organizations/invitations/'
      preLoaderRoute: typeof OrganizationsInvitationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings/': {
      id: '/dashboard/settings/'
      path: '/settings'
      fullPath: '/dashboard/settings/'
      preLoaderRoute: typeof DashboardSettingsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/roles/': {
      id: '/dashboard/roles/'
      path: '/roles'
      fullPath: '/dashboard/roles/'
      preLoaderRoute: typeof DashboardRolesIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/members/': {
      id: '/dashboard/members/'
      path: '/members'
      fullPath: '/dashboard/members/'
      preLoaderRoute: typeof DashboardMembersIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/invitations/': {
      id: '/dashboard/invitations/'
      path: '/invitations'
      fullPath: '/dashboard/invitations/'
      preLoaderRoute: typeof DashboardInvitationsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/roles/new/': {
      id: '/dashboard/roles/new/'
      path: '/roles/new'
      fullPath: '/dashboard/roles/new/'
      preLoaderRoute: typeof DashboardRolesNewIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/members/invite/': {
      id: '/dashboard/members/invite/'
      path: '/members/invite'
      fullPath: '/dashboard/members/invite/'
      preLoaderRoute: typeof DashboardMembersInviteIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/members/$memberId/edit/': {
      id: '/dashboard/members/$memberId/edit/'
      path: '/members/$memberId/edit'
      fullPath: '/dashboard/members/$memberId/edit/'
      preLoaderRoute: typeof DashboardMembersMemberIdEditIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardInvitationsIndexRoute: typeof DashboardInvitationsIndexRoute
  DashboardMembersIndexRoute: typeof DashboardMembersIndexRoute
  DashboardRolesIndexRoute: typeof DashboardRolesIndexRoute
  DashboardSettingsIndexRoute: typeof DashboardSettingsIndexRoute
  DashboardMembersInviteIndexRoute: typeof DashboardMembersInviteIndexRoute
  DashboardRolesNewIndexRoute: typeof DashboardRolesNewIndexRoute
  DashboardMembersMemberIdEditIndexRoute: typeof DashboardMembersMemberIdEditIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardInvitationsIndexRoute: DashboardInvitationsIndexRoute,
  DashboardMembersIndexRoute: DashboardMembersIndexRoute,
  DashboardRolesIndexRoute: DashboardRolesIndexRoute,
  DashboardSettingsIndexRoute: DashboardSettingsIndexRoute,
  DashboardMembersInviteIndexRoute: DashboardMembersInviteIndexRoute,
  DashboardRolesNewIndexRoute: DashboardRolesNewIndexRoute,
  DashboardMembersMemberIdEditIndexRoute:
    DashboardMembersMemberIdEditIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  OrganizationsIndexRoute: OrganizationsIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  SignInIndexRoute: SignInIndexRoute,
  SignUpIndexRoute: SignUpIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  OrganizationsInvitationsIndexRoute: OrganizationsInvitationsIndexRoute,
  OrganizationsNewIndexRoute: OrganizationsNewIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
